/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalSupplierRole;

import Business.Organizations.MedicalSupplierOrganization;
import Business.Organizations.Organization;
import Business.UserAccount.UserAccountMedicalSupplier.UserAccountMedicalSupplier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author halder.r
 */
public class ManageMedicalSuppliesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMedicalSuppliesJPanel
     */
    private JPanel userProcessContainer;
    private UserAccountMedicalSupplier account;
    private MedicalSupplierOrganization organization;

    public ManageMedicalSuppliesJPanel(JPanel userProcessContainer, UserAccountMedicalSupplier account, Organization organization) {
        try {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.account = account;
            this.organization = (MedicalSupplierOrganization) organization;
            populateTable();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("medicalsupply.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jPanel2 = new javax.swing.JPanel();
        addNewMedicalItemButton = new javax.swing.JButton();
        updateMedicalItemButton = new javax.swing.JButton();
        deleteMedicalItemButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalSupplyjTable = new javax.swing.JTable();
        medicalSupplyLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewMedicalItemButton.setBackground(new java.awt.Color(51, 153, 255));
        addNewMedicalItemButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addNewMedicalItemButton.setForeground(java.awt.Color.white);
        addNewMedicalItemButton.setText("ADD");
        addNewMedicalItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMedicalItemButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addNewMedicalItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, 30));

        updateMedicalItemButton.setBackground(new java.awt.Color(51, 153, 255));
        updateMedicalItemButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        updateMedicalItemButton.setForeground(java.awt.Color.white);
        updateMedicalItemButton.setText("UPDATE");
        updateMedicalItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMedicalItemButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateMedicalItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 160, 30));

        deleteMedicalItemButton.setBackground(new java.awt.Color(51, 153, 255));
        deleteMedicalItemButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteMedicalItemButton.setForeground(java.awt.Color.white);
        deleteMedicalItemButton.setText("DELETE");
        deleteMedicalItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMedicalItemButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteMedicalItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 170, 30));

        medicalSupplyjTable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        medicalSupplyjTable.setForeground(new java.awt.Color(51, 153, 255));
        medicalSupplyjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        medicalSupplyjTable.setRowHeight(24);
        jScrollPane1.setViewportView(medicalSupplyjTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 590, 200));

        medicalSupplyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        medicalSupplyLabel.setForeground(new java.awt.Color(153, 153, 153));
        medicalSupplyLabel.setText("MANAGE MEDICAL SUPPLY");
        jPanel2.add(medicalSupplyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 340, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 640, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 590, 10));

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        backButton.setForeground(java.awt.Color.white);
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 660, 490));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addNewMedicalItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMedicalItemButtonActionPerformed
        try {
            AddNewMedicalItemPanel addNewMedicalItemPanel = new AddNewMedicalItemPanel(userProcessContainer, account, organization);
            userProcessContainer.add("addNewMedicalItemPanel", addNewMedicalItemPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_addNewMedicalItemButtonActionPerformed

    private void updateMedicalItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMedicalItemButtonActionPerformed
        try {
            if (medicalSupplyjTable.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(null, "Select a row to update!");
            } else {
                UpdateMedicalitemPanel updateMedicalitemPanel = new UpdateMedicalitemPanel(userProcessContainer, account, organization, medicalSupplyjTable.getValueAt(medicalSupplyjTable.getSelectedRow(), 0).toString(), Integer.parseInt(medicalSupplyjTable.getValueAt(medicalSupplyjTable.getSelectedRow(), 1).toString()));
                userProcessContainer.add("updateMedicalitemPanel", updateMedicalitemPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_updateMedicalItemButtonActionPerformed

    private void deleteMedicalItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMedicalItemButtonActionPerformed
        try {
            if (medicalSupplyjTable.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(null, "Select a row to update!");
            } else {
                organization.getMedicalSuppliesInventory().getMedicalInventory().remove(medicalSupplyjTable.getValueAt(medicalSupplyjTable.getSelectedRow(), 0));
                JOptionPane.showMessageDialog(null, "The item is deleted!");
                populateTable();
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_deleteMedicalItemButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            userProcessContainer.remove(this);

            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            MedicalSupplierWorkAreaJPanel dwjp = (MedicalSupplierWorkAreaJPanel) component;
            dwjp.populateTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_backButtonActionPerformed

    public void populateTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) medicalSupplyjTable.getModel();

            model.setRowCount(0);
            Iterator it = organization.getMedicalSuppliesInventory().getMedicalInventory().entrySet().iterator();
            while (it.hasNext()) {
                Map.Entry pair = (Map.Entry) it.next();
                Object[] row = new Object[4];
                row[0] = pair.getKey();
                row[1] = pair.getValue();
                model.addRow(row);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewMedicalItemButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteMedicalItemButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel medicalSupplyLabel;
    private javax.swing.JTable medicalSupplyjTable;
    private javax.swing.JButton updateMedicalItemButton;
    // End of variables declaration//GEN-END:variables
}
