/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalSupplierRole;

import Business.Organizations.MedicalSupplierOrganization;
import Business.UserAccount.UserAccountMedicalSupplier.UserAccountMedicalSupplier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author halder.r
 */
public class UpdateMedicalitemPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccountMedicalSupplier account;
    private MedicalSupplierOrganization organization;
    private String name;

    public UpdateMedicalitemPanel(JPanel userProcessContainer, UserAccountMedicalSupplier account, MedicalSupplierOrganization organization, String name, Integer quantity) {
        try {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.account = account;
            this.organization = organization;
            nameTextField.setText(name);
            quantityTextField.setText(quantity.toString());
            this.name = name;
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("medicalsupply.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jPanel2 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        quantityTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelButton.setBackground(new java.awt.Color(51, 153, 255));
        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cancelButton.setForeground(java.awt.Color.white);
        cancelButton.setText("BACK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 30));

        saveButton.setBackground(new java.awt.Color(51, 153, 255));
        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        saveButton.setForeground(java.awt.Color.white);
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 30));

        quantityTextField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 215, -1));

        nameTextField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 215, -1));

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("UPDATE MEDICAL SUPPLY");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("NAME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("QUANTITY:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 360, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 600, 420));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Iterator it = organization.getMedicalSuppliesInventory().getMedicalInventory().entrySet().iterator();
            while (it.hasNext()) {
                Map.Entry pair = (Map.Entry) it.next();
                if (pair.getKey().equals(name)) {
                    if (!name.equals(nameTextField.getText())) {
                        Object obj = organization.getMedicalSuppliesInventory().getMedicalInventory().remove(name);
                        organization.getMedicalSuppliesInventory().getMedicalInventory().put(nameTextField.getText(), Integer.parseInt(quantityTextField.getText()));
                        JOptionPane.showMessageDialog(null, "Medical Item Updated!");
                        userProcessContainer.remove(this);
                        Component[] componentArray = userProcessContainer.getComponents();
                        Component component = componentArray[componentArray.length - 1];
                        ManageMedicalSuppliesJPanel dwjp = (ManageMedicalSuppliesJPanel) component;
                        dwjp.populateTable();
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.previous(userProcessContainer);
                    } else {
                        organization.getMedicalSuppliesInventory().getMedicalInventory().put(name, Integer.parseInt(quantityTextField.getText()));
                        JOptionPane.showMessageDialog(null, "Medical Item Updated!");
                        userProcessContainer.remove(this);
                        Component[] componentArray = userProcessContainer.getComponents();
                        Component component = componentArray[componentArray.length - 1];
                        ManageMedicalSuppliesJPanel dwjp = (ManageMedicalSuppliesJPanel) component;
                        dwjp.populateTable();
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.previous(userProcessContainer);
                    }
                }
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            userProcessContainer.remove(this);

            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ManageMedicalSuppliesJPanel dwjp = (ManageMedicalSuppliesJPanel) component;
            dwjp.populateTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
