/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organizations.Organization;
import Business.Organizations.Organization.Type;
import Business.Organizations.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raunak
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise.EnterpriseType enterpriseType;
    private Enterprise enterprise;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory, Enterprise.EnterpriseType enterpriseType, Enterprise enterprise) {
        try {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.directory = directory;
            this.enterpriseType = enterpriseType;
            this.enterprise = enterprise;
            populateTable();
            populateCombo(enterpriseType);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }

    private void populateCombo(Enterprise.EnterpriseType enterpriseType) {
        organizationJComboBox.removeAllItems();
        switch (enterpriseType) {
            case ArmedForces:
                organizationJComboBox.addItem(Organization.Type.Soldiers);
                organizationJComboBox.addItem(Organization.Type.Doctors);
                break;
            case MedicalSuppliers:
                organizationJComboBox.addItem(Organization.Type.MedicalSuppliers);
                break;
            case FoodSuppliers:
                organizationJComboBox.addItem(Organization.Type.FoodSuppliers);
                break;
            default:
                break;
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

        directory.getOrganizationList().stream().map((organization) -> {
            Object[] row = new Object[2];
            row[0] = organization;
            return row;
        }).forEachOrdered((row) -> {
            model.addRow(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("bluesky.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);
            }};
            jScrollPane1 = new javax.swing.JScrollPane();
            organizationJTable = new javax.swing.JTable();
            organizationJComboBox = new javax.swing.JComboBox();
            jLabel1 = new javax.swing.JLabel();
            orgNameLabel = new javax.swing.JLabel();
            longitudeTxt = new javax.swing.JTextField();
            addJButton = new javax.swing.JButton();
            backJButton = new javax.swing.JButton();
            jSeparator1 = new javax.swing.JSeparator();
            jSeparator2 = new javax.swing.JSeparator();
            orgNameLabel1 = new javax.swing.JLabel();
            jSeparator3 = new javax.swing.JSeparator();
            deleteJButton = new javax.swing.JButton();
            orgNameLabel2 = new javax.swing.JLabel();
            orgNameTxt = new javax.swing.JTextField();
            orgNameLabel3 = new javax.swing.JLabel();
            latitudeTxt = new javax.swing.JTextField();

            setLayout(new java.awt.BorderLayout());

            jPanel1.setForeground(java.awt.Color.white);
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            organizationJTable.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Name"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            organizationJTable.setRowHeight(36);
            jScrollPane1.setViewportView(organizationJTable);
            if (organizationJTable.getColumnModel().getColumnCount() > 0) {
                organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            }

            jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 380, 180));

            organizationJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            organizationJComboBox.setForeground(new java.awt.Color(51, 153, 255));
            organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jPanel1.add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 390, -1));

            jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            jLabel1.setForeground(java.awt.Color.white);
            jLabel1.setText("ORGANIZATION TYPE:");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 400, -1));

            orgNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            orgNameLabel.setForeground(java.awt.Color.white);
            orgNameLabel.setText("ORGANIZATION:");
            jPanel1.add(orgNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 310, -1));

            longitudeTxt.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            longitudeTxt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    longitudeTxtActionPerformed(evt);
                }
            });
            jPanel1.add(longitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 210, -1));

            addJButton.setBackground(new java.awt.Color(51, 153, 255));
            addJButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            addJButton.setForeground(java.awt.Color.white);
            addJButton.setText("ADD");
            addJButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addJButtonActionPerformed(evt);
                }
            });
            jPanel1.add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 720, 170, -1));

            backJButton.setBackground(new java.awt.Color(51, 153, 255));
            backJButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
            backJButton.setForeground(java.awt.Color.white);
            backJButton.setText("<< BACK");
            backJButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    backJButtonActionPerformed(evt);
                }
            });
            jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, 190, -1));
            jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 390, 10));
            jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 390, 20));

            orgNameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            orgNameLabel1.setForeground(java.awt.Color.white);
            orgNameLabel1.setText("Longitude");
            jPanel1.add(orgNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 160, -1));
            jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 330, 20));

            deleteJButton.setBackground(new java.awt.Color(51, 153, 255));
            deleteJButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
            deleteJButton.setForeground(new java.awt.Color(255, 255, 255));
            deleteJButton.setText("Delete");
            deleteJButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    deleteJButtonActionPerformed(evt);
                }
            });
            jPanel1.add(deleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 720, 240, 50));

            orgNameLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            orgNameLabel2.setForeground(java.awt.Color.white);
            orgNameLabel2.setText("ORGANIZATION NAME:");
            jPanel1.add(orgNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 400, -1));

            orgNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            orgNameTxt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    orgNameTxtActionPerformed(evt);
                }
            });
            jPanel1.add(orgNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 380, -1));

            orgNameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            orgNameLabel3.setForeground(java.awt.Color.white);
            orgNameLabel3.setText("Latitude");
            jPanel1.add(orgNameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 160, -1));

            latitudeTxt.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
            latitudeTxt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    latitudeTxtActionPerformed(evt);
                }
            });
            jPanel1.add(latitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 210, -1));

            add(jPanel1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        try {
            Type type = (Type) organizationJComboBox.getSelectedItem();
            String Orgname = orgNameTxt.getText();
            String latitude = latitudeTxt.getText();
            String longitude = longitudeTxt.getText();
            directory.createOrganization(type, Orgname, longitude, latitude);
            populateTable();
            longitudeTxt.setText("");
            latitudeTxt.setText("");
            orgNameTxt.setText("");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        try {
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_backJButtonActionPerformed

    private void longitudeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudeTxtActionPerformed

    }//GEN-LAST:event_longitudeTxtActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = organizationJTable.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(null, "Please select a row.");
            } else {
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
                if (selectionResult == JOptionPane.YES_OPTION) {
                    Organization org = (Organization) organizationJTable.getValueAt(selectedRow, 0);
                    for (Organization s1 : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (s1 == org) {
                            enterprise.getOrganizationDirectory().removeOrganization(s1);
                            JOptionPane.showMessageDialog(null, org.getName() + " removed from the enterprise!");
                            break;
                        }
                    }
                    longitudeTxt.setText("");
                    populateTable();
                }
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void orgNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgNameTxtActionPerformed

    private void latitudeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudeTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField latitudeTxt;
    private javax.swing.JTextField longitudeTxt;
    private javax.swing.JLabel orgNameLabel;
    private javax.swing.JLabel orgNameLabel1;
    private javax.swing.JLabel orgNameLabel2;
    private javax.swing.JLabel orgNameLabel3;
    private javax.swing.JTextField orgNameTxt;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
