/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CampCommandantRole;

import userinterface.DoctorRole.DoctorWorkAreaJPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Notifications.Send;
import Business.Organizations.MedicalCampOrganization;
import Business.Organizations.MilitaryCampOrganization;
import Business.Organizations.Organization;
import Business.UserAccount.UserAccountSoldier.UserAccountSoldier;
import Business.RequestQueue.NewRequestToCampCommandant;
import Business.RequestQueue.NewRequestToDoctor;
import Business.Role.Role;
import Business.Soldiers.Soldiers;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestToDoctorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccountSoldier userAccount;
    private EcoSystem system;
    private static int pdfCount = 0;
    private Send send = new Send();

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestToDoctorJPanel(JPanel userProcessContainer, UserAccountSoldier account, Enterprise enterprise, EcoSystem business) {
        try {
            initComponents();

            this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.userAccount = account;
            this.system = business;
            valueLabel.setText(enterprise.getName());
            populateCategoryComboBox();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        requestComboBox = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        saveAsPDFButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Send Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Request a Doctor");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 330, 30));

        jLabel2.setText("Request Category");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        requestComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(requestComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 290, -1));

        jLabel3.setText("Description");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        saveAsPDFButton.setText("Save As PDF");
        saveAsPDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsPDFButtonActionPerformed(evt);
            }
        });
        add(saveAsPDFButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        try {
            String message = descriptionTextArea.getText();
            String requestCat = requestComboBox.getSelectedItem().toString();
            NewRequestToDoctor request = new NewRequestToDoctor();
            request.setMessage(message);
            request.setRequestCategory(requestCat);
            request.setSender(userAccount);
            request.setStatus("Sent");

//            Organization org = null;
            ArrayList<Organization> orgList = new ArrayList<Organization>();
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof MedicalCampOrganization) {
                    orgList.add(organization);
                }
            }
            for (Organization org : orgList) {
            if (org != null) {
                org.getRequestQueueCampCommandantDoctor().getWorkRequestCampCommandantDoctor().add(request);
            }
            }
            
                userAccount.getRequestQueueCampCommandantDoctor().getWorkRequestCampCommandantDoctor().add(request);
            String recepient = "";
            for (UserAccount ua : enterprise.getSoldierUADirectory().getUserAccountList()) {
                if (ua.getEmail() != null) {
                    recepient = recepient + ua.getEmail() + ",";
                }
            }
            if (!recepient.isEmpty()) {
                send.mail(recepient, requestCat, message);
            }
            JOptionPane.showMessageDialog(null, "Request succesfully sent to doctors");
            descriptionTextArea.setText("");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        try {
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            CampCommandantWorkAreaJPanel ccqjp = (CampCommandantWorkAreaJPanel) component;
            ccqjp.populateDoctorRequestTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Null Pointer Exception Occurred!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some Exception Occurred!");
        }
    }//GEN-LAST:event_backJButtonActionPerformed

    private void populateCategoryComboBox() {
        requestComboBox.removeAllItems();
        requestComboBox.addItem(Soldiers.RequestCategory.SendingPatients.getValue());
        requestComboBox.addItem(Soldiers.RequestCategory.MedicalSupplies.getValue());
        requestComboBox.addItem(Soldiers.RequestCategory.RelievingNurse.getValue());
    }

    private void saveAsPDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsPDFButtonActionPerformed
        Document newDocument = new Document();
        String myFilepath = userAccount.getUsername() + "_RequestToDoctor_" + pdfCount + ".pdf";
        try {
            PdfWriter.getInstance(newDocument, new FileOutputStream(userAccount.getUsername() + "_RequestToCampCommandant_" + pdfCount + ".pdf"));
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(RequestToDoctorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            newDocument.open();
            newDocument.add(new Paragraph("Hi,"));
            newDocument.add(new Paragraph(userAccount.getUsername().toUpperCase()));
            newDocument.add(new Paragraph(" "));
            newDocument.add(new Paragraph("Your Request has been send to Doctor."));
            newDocument.add(new Paragraph(" "));
            newDocument.add(new Paragraph("Request Category - " + requestComboBox.getSelectedItem()));
            newDocument.add(new Paragraph("Request Description - " + descriptionTextArea.getText()));
            newDocument.add(new Paragraph(" "));
            newDocument.add(new Paragraph("Thanks."));
            newDocument.close();
            JOptionPane.showMessageDialog(null, " Report Generated where the project is placed!");
            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File(myFilepath);
                    Desktop.getDesktop().open(myFile);
                } catch (IOException ex) {

                }
            }

        } catch (DocumentException ex) {
            Logger.getLogger(RequestToDoctorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        pdfCount += 1;
    }//GEN-LAST:event_saveAsPDFButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> requestComboBox;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton saveAsPDFButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
