/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodSupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.FoodSupplierOrganization;
import Business.Organizations.Organization;
import userinterface.MedicalSupplierRole.*;
import Business.RequestQueue.NewRequestToCampCommandant;
import Business.RequestQueue.NewRequestToFoodSupplier;
import Business.RequestQueue.WorkRequestCampCommandantFoodSupplier;
import Business.UserAccount.UserAccount;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;



public class ProcessWorkRequestCampCommandantFoodSupplierJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NewRequestToFoodSupplier request;
    private FoodSupplierOrganization foodSupplierOrganization;
    private EcoSystem business;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestCampCommandantFoodSupplierJPanel(JPanel userProcessContainer, NewRequestToFoodSupplier request,FoodSupplierOrganization foodSupplierOrganization,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.foodSupplierOrganization= foodSupplierOrganization;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {
                ImageIcon img=new ImageIcon("food.jpg");
                Image i=img.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jPanel2 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        justificationTextField = new javax.swing.JTextField();
        resultComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(51, 153, 255));
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        jPanel2.add(justificationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 79, 380, 101));

        resultComboBox.setBackground(new java.awt.Color(51, 153, 255));
        resultComboBox.setForeground(new java.awt.Color(255, 255, 255));
        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Rejected" }));
        jPanel2.add(resultComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setText("Result");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setText("Justification");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        backJButton.setBackground(new java.awt.Color(51, 153, 255));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 460, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 510, 260));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FoodSupplierWorkAreaJPanel dwjp = (FoodSupplierWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setResult(justificationTextField.getText());
        request.setStatus(resultComboBox.getSelectedItem().toString());
        if("Aproved".equals(resultComboBox.getSelectedItem().toString())){
   //     distributeItem(request);
        }
        JOptionPane.showMessageDialog(null, "Request has been "+resultComboBox.getSelectedItem().toString()+" Succesfully");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FoodSupplierWorkAreaJPanel dwjp = (FoodSupplierWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_submitJButtonActionPerformed

//    public void distributeItem(NewRequestToFoodSupplier request){
//        foodSupplierOrganization.getFoodSuppliesInventory().getFoodInventory();
//         
//        
//
//    for(Network network : business.getNetworkList()){
//            for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
//                for(Organization org1: ent.getOrganizationDirectory().getOrganizationList()){
//                    
//                        FoodSupplierOrganization fsOrg = (FoodSupplierOrganization)org1;
//                        Iterator it = fsOrg.getFoodSuppliesInventory().getFoodInventory().entrySet().iterator();
//                        while (it.hasNext()) {
//                            Map.Entry pair = (Map.Entry)it.next();
//                            if(pair.getKey().equals(request.getFoodSupplies().getFoodName())){
//                                pair.setValue(Integer.parseInt(pair.getValue().toString())-request.getFoodSupplies().getQuantity());
//                                break;
//                            }
//                        }
//                }
//            }
//        }
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField justificationTextField;
    private javax.swing.JComboBox<String> resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
